//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1022
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPAdmPre.BL.serviceWSSpring {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://royalsystems.net/", ConfigurationName="serviceWSSpring.WSSpringSoap")]
    public interface WSSpringSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento str_pApellidoPaterno del espacio de nombres http://royalsystems.net/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://royalsystems.net/WM_InsertarCliente", ReplyAction="*")]
        UPAdmPre.BL.serviceWSSpring.WM_InsertarClienteResponse WM_InsertarCliente(UPAdmPre.BL.serviceWSSpring.WM_InsertarClienteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento str_pCentroCosto del espacio de nombres http://royalsystems.net/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://royalsystems.net/WM_ListarCronogramaPagos", ReplyAction="*")]
        UPAdmPre.BL.serviceWSSpring.WM_ListarCronogramaPagosResponse WM_ListarCronogramaPagos(UPAdmPre.BL.serviceWSSpring.WM_ListarCronogramaPagosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento str_pCliente del espacio de nombres http://royalsystems.net/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://royalsystems.net/WM_ListarDocumentosResumen", ReplyAction="*")]
        UPAdmPre.BL.serviceWSSpring.WM_ListarDocumentosResumenResponse WM_ListarDocumentosResumen(UPAdmPre.BL.serviceWSSpring.WM_ListarDocumentosResumenRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento str_pCliente del espacio de nombres http://royalsystems.net/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://royalsystems.net/WM_ListarDocumentosDetalle", ReplyAction="*")]
        UPAdmPre.BL.serviceWSSpring.WM_ListarDocumentosDetalleResponse WM_ListarDocumentosDetalle(UPAdmPre.BL.serviceWSSpring.WM_ListarDocumentosDetalleRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento str_pCliente del espacio de nombres http://royalsystems.net/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://royalsystems.net/WM_TraerEstadoDeuda", ReplyAction="*")]
        UPAdmPre.BL.serviceWSSpring.WM_TraerEstadoDeudaResponse WM_TraerEstadoDeuda(UPAdmPre.BL.serviceWSSpring.WM_TraerEstadoDeudaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento str_pCodigoCompania del espacio de nombres http://royalsystems.net/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://royalsystems.net/WM_InsertarCobranza", ReplyAction="*")]
        UPAdmPre.BL.serviceWSSpring.WM_InsertarCobranzaResponse WM_InsertarCobranza(UPAdmPre.BL.serviceWSSpring.WM_InsertarCobranzaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WM_InsertarClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WM_InsertarCliente", Namespace="http://royalsystems.net/", Order=0)]
        public UPAdmPre.BL.serviceWSSpring.WM_InsertarClienteRequestBody Body;
        
        public WM_InsertarClienteRequest() {
        }
        
        public WM_InsertarClienteRequest(UPAdmPre.BL.serviceWSSpring.WM_InsertarClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://royalsystems.net/")]
    public partial class WM_InsertarClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str_pApellidoPaterno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string str_pApellidoMaterno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string str_pNombres;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string str_pRazonSocial;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string str_pTipoDocumento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string str_pNumeroDocumento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string str_pDocumentoFiscal;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string str_pFechaNacimiento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string str_pDireccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string str_pCorreoElectronico;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string str_pTelefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string str_pPersonaAnterior;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string str_pClasePersona;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string str_pTipoDocumentoPago;
        
        public WM_InsertarClienteRequestBody() {
        }
        
        public WM_InsertarClienteRequestBody(string str_pApellidoPaterno, string str_pApellidoMaterno, string str_pNombres, string str_pRazonSocial, string str_pTipoDocumento, string str_pNumeroDocumento, string str_pDocumentoFiscal, string str_pFechaNacimiento, string str_pDireccion, string str_pCorreoElectronico, string str_pTelefono, string str_pPersonaAnterior, string str_pClasePersona, string str_pTipoDocumentoPago) {
            this.str_pApellidoPaterno = str_pApellidoPaterno;
            this.str_pApellidoMaterno = str_pApellidoMaterno;
            this.str_pNombres = str_pNombres;
            this.str_pRazonSocial = str_pRazonSocial;
            this.str_pTipoDocumento = str_pTipoDocumento;
            this.str_pNumeroDocumento = str_pNumeroDocumento;
            this.str_pDocumentoFiscal = str_pDocumentoFiscal;
            this.str_pFechaNacimiento = str_pFechaNacimiento;
            this.str_pDireccion = str_pDireccion;
            this.str_pCorreoElectronico = str_pCorreoElectronico;
            this.str_pTelefono = str_pTelefono;
            this.str_pPersonaAnterior = str_pPersonaAnterior;
            this.str_pClasePersona = str_pClasePersona;
            this.str_pTipoDocumentoPago = str_pTipoDocumentoPago;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WM_InsertarClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WM_InsertarClienteResponse", Namespace="http://royalsystems.net/", Order=0)]
        public UPAdmPre.BL.serviceWSSpring.WM_InsertarClienteResponseBody Body;
        
        public WM_InsertarClienteResponse() {
        }
        
        public WM_InsertarClienteResponse(UPAdmPre.BL.serviceWSSpring.WM_InsertarClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://royalsystems.net/")]
    public partial class WM_InsertarClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string WM_InsertarClienteResult;
        
        public WM_InsertarClienteResponseBody() {
        }
        
        public WM_InsertarClienteResponseBody(string WM_InsertarClienteResult) {
            this.WM_InsertarClienteResult = WM_InsertarClienteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WM_ListarCronogramaPagosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WM_ListarCronogramaPagos", Namespace="http://royalsystems.net/", Order=0)]
        public UPAdmPre.BL.serviceWSSpring.WM_ListarCronogramaPagosRequestBody Body;
        
        public WM_ListarCronogramaPagosRequest() {
        }
        
        public WM_ListarCronogramaPagosRequest(UPAdmPre.BL.serviceWSSpring.WM_ListarCronogramaPagosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://royalsystems.net/")]
    public partial class WM_ListarCronogramaPagosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str_pCentroCosto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string str_pProyecto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string str_pPeriodo;
        
        public WM_ListarCronogramaPagosRequestBody() {
        }
        
        public WM_ListarCronogramaPagosRequestBody(string str_pCentroCosto, string str_pProyecto, string str_pPeriodo) {
            this.str_pCentroCosto = str_pCentroCosto;
            this.str_pProyecto = str_pProyecto;
            this.str_pPeriodo = str_pPeriodo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WM_ListarCronogramaPagosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WM_ListarCronogramaPagosResponse", Namespace="http://royalsystems.net/", Order=0)]
        public UPAdmPre.BL.serviceWSSpring.WM_ListarCronogramaPagosResponseBody Body;
        
        public WM_ListarCronogramaPagosResponse() {
        }
        
        public WM_ListarCronogramaPagosResponse(UPAdmPre.BL.serviceWSSpring.WM_ListarCronogramaPagosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://royalsystems.net/")]
    public partial class WM_ListarCronogramaPagosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string WM_ListarCronogramaPagosResult;
        
        public WM_ListarCronogramaPagosResponseBody() {
        }
        
        public WM_ListarCronogramaPagosResponseBody(string WM_ListarCronogramaPagosResult) {
            this.WM_ListarCronogramaPagosResult = WM_ListarCronogramaPagosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WM_ListarDocumentosResumenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WM_ListarDocumentosResumen", Namespace="http://royalsystems.net/", Order=0)]
        public UPAdmPre.BL.serviceWSSpring.WM_ListarDocumentosResumenRequestBody Body;
        
        public WM_ListarDocumentosResumenRequest() {
        }
        
        public WM_ListarDocumentosResumenRequest(UPAdmPre.BL.serviceWSSpring.WM_ListarDocumentosResumenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://royalsystems.net/")]
    public partial class WM_ListarDocumentosResumenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str_pCliente;
        
        public WM_ListarDocumentosResumenRequestBody() {
        }
        
        public WM_ListarDocumentosResumenRequestBody(string str_pCliente) {
            this.str_pCliente = str_pCliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WM_ListarDocumentosResumenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WM_ListarDocumentosResumenResponse", Namespace="http://royalsystems.net/", Order=0)]
        public UPAdmPre.BL.serviceWSSpring.WM_ListarDocumentosResumenResponseBody Body;
        
        public WM_ListarDocumentosResumenResponse() {
        }
        
        public WM_ListarDocumentosResumenResponse(UPAdmPre.BL.serviceWSSpring.WM_ListarDocumentosResumenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://royalsystems.net/")]
    public partial class WM_ListarDocumentosResumenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string WM_ListarDocumentosResumenResult;
        
        public WM_ListarDocumentosResumenResponseBody() {
        }
        
        public WM_ListarDocumentosResumenResponseBody(string WM_ListarDocumentosResumenResult) {
            this.WM_ListarDocumentosResumenResult = WM_ListarDocumentosResumenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WM_ListarDocumentosDetalleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WM_ListarDocumentosDetalle", Namespace="http://royalsystems.net/", Order=0)]
        public UPAdmPre.BL.serviceWSSpring.WM_ListarDocumentosDetalleRequestBody Body;
        
        public WM_ListarDocumentosDetalleRequest() {
        }
        
        public WM_ListarDocumentosDetalleRequest(UPAdmPre.BL.serviceWSSpring.WM_ListarDocumentosDetalleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://royalsystems.net/")]
    public partial class WM_ListarDocumentosDetalleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str_pCliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string str_pCentroCosto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string str_pProyecto;
        
        public WM_ListarDocumentosDetalleRequestBody() {
        }
        
        public WM_ListarDocumentosDetalleRequestBody(string str_pCliente, string str_pCentroCosto, string str_pProyecto) {
            this.str_pCliente = str_pCliente;
            this.str_pCentroCosto = str_pCentroCosto;
            this.str_pProyecto = str_pProyecto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WM_ListarDocumentosDetalleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WM_ListarDocumentosDetalleResponse", Namespace="http://royalsystems.net/", Order=0)]
        public UPAdmPre.BL.serviceWSSpring.WM_ListarDocumentosDetalleResponseBody Body;
        
        public WM_ListarDocumentosDetalleResponse() {
        }
        
        public WM_ListarDocumentosDetalleResponse(UPAdmPre.BL.serviceWSSpring.WM_ListarDocumentosDetalleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://royalsystems.net/")]
    public partial class WM_ListarDocumentosDetalleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string WM_ListarDocumentosDetalleResult;
        
        public WM_ListarDocumentosDetalleResponseBody() {
        }
        
        public WM_ListarDocumentosDetalleResponseBody(string WM_ListarDocumentosDetalleResult) {
            this.WM_ListarDocumentosDetalleResult = WM_ListarDocumentosDetalleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WM_TraerEstadoDeudaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WM_TraerEstadoDeuda", Namespace="http://royalsystems.net/", Order=0)]
        public UPAdmPre.BL.serviceWSSpring.WM_TraerEstadoDeudaRequestBody Body;
        
        public WM_TraerEstadoDeudaRequest() {
        }
        
        public WM_TraerEstadoDeudaRequest(UPAdmPre.BL.serviceWSSpring.WM_TraerEstadoDeudaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://royalsystems.net/")]
    public partial class WM_TraerEstadoDeudaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str_pCliente;
        
        public WM_TraerEstadoDeudaRequestBody() {
        }
        
        public WM_TraerEstadoDeudaRequestBody(string str_pCliente) {
            this.str_pCliente = str_pCliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WM_TraerEstadoDeudaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WM_TraerEstadoDeudaResponse", Namespace="http://royalsystems.net/", Order=0)]
        public UPAdmPre.BL.serviceWSSpring.WM_TraerEstadoDeudaResponseBody Body;
        
        public WM_TraerEstadoDeudaResponse() {
        }
        
        public WM_TraerEstadoDeudaResponse(UPAdmPre.BL.serviceWSSpring.WM_TraerEstadoDeudaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://royalsystems.net/")]
    public partial class WM_TraerEstadoDeudaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string WM_TraerEstadoDeudaResult;
        
        public WM_TraerEstadoDeudaResponseBody() {
        }
        
        public WM_TraerEstadoDeudaResponseBody(string WM_TraerEstadoDeudaResult) {
            this.WM_TraerEstadoDeudaResult = WM_TraerEstadoDeudaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WM_InsertarCobranzaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WM_InsertarCobranza", Namespace="http://royalsystems.net/", Order=0)]
        public UPAdmPre.BL.serviceWSSpring.WM_InsertarCobranzaRequestBody Body;
        
        public WM_InsertarCobranzaRequest() {
        }
        
        public WM_InsertarCobranzaRequest(UPAdmPre.BL.serviceWSSpring.WM_InsertarCobranzaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://royalsystems.net/")]
    public partial class WM_InsertarCobranzaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str_pCodigoCompania;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string str_pCodigoCliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string str_pFechaPreparacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string str_pCodigoCobrador;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string str_pCodigoCajero;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string str_pTipoDocumento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string str_pNumeroDocumento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string str_pMonedaPago;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string str_pMontoPagado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string str_pTipoPago;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string str_pDocumentoReferencia;
        
        public WM_InsertarCobranzaRequestBody() {
        }
        
        public WM_InsertarCobranzaRequestBody(string str_pCodigoCompania, string str_pCodigoCliente, string str_pFechaPreparacion, string str_pCodigoCobrador, string str_pCodigoCajero, string str_pTipoDocumento, string str_pNumeroDocumento, string str_pMonedaPago, string str_pMontoPagado, string str_pTipoPago, string str_pDocumentoReferencia) {
            this.str_pCodigoCompania = str_pCodigoCompania;
            this.str_pCodigoCliente = str_pCodigoCliente;
            this.str_pFechaPreparacion = str_pFechaPreparacion;
            this.str_pCodigoCobrador = str_pCodigoCobrador;
            this.str_pCodigoCajero = str_pCodigoCajero;
            this.str_pTipoDocumento = str_pTipoDocumento;
            this.str_pNumeroDocumento = str_pNumeroDocumento;
            this.str_pMonedaPago = str_pMonedaPago;
            this.str_pMontoPagado = str_pMontoPagado;
            this.str_pTipoPago = str_pTipoPago;
            this.str_pDocumentoReferencia = str_pDocumentoReferencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WM_InsertarCobranzaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WM_InsertarCobranzaResponse", Namespace="http://royalsystems.net/", Order=0)]
        public UPAdmPre.BL.serviceWSSpring.WM_InsertarCobranzaResponseBody Body;
        
        public WM_InsertarCobranzaResponse() {
        }
        
        public WM_InsertarCobranzaResponse(UPAdmPre.BL.serviceWSSpring.WM_InsertarCobranzaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://royalsystems.net/")]
    public partial class WM_InsertarCobranzaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string WM_InsertarCobranzaResult;
        
        public WM_InsertarCobranzaResponseBody() {
        }
        
        public WM_InsertarCobranzaResponseBody(string WM_InsertarCobranzaResult) {
            this.WM_InsertarCobranzaResult = WM_InsertarCobranzaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSSpringSoapChannel : UPAdmPre.BL.serviceWSSpring.WSSpringSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSSpringSoapClient : System.ServiceModel.ClientBase<UPAdmPre.BL.serviceWSSpring.WSSpringSoap>, UPAdmPre.BL.serviceWSSpring.WSSpringSoap {
        
        public WSSpringSoapClient() {
        }
        
        public WSSpringSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSSpringSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSSpringSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSSpringSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPAdmPre.BL.serviceWSSpring.WM_InsertarClienteResponse UPAdmPre.BL.serviceWSSpring.WSSpringSoap.WM_InsertarCliente(UPAdmPre.BL.serviceWSSpring.WM_InsertarClienteRequest request) {
            return base.Channel.WM_InsertarCliente(request);
        }
        
        public string WM_InsertarCliente(string str_pApellidoPaterno, string str_pApellidoMaterno, string str_pNombres, string str_pRazonSocial, string str_pTipoDocumento, string str_pNumeroDocumento, string str_pDocumentoFiscal, string str_pFechaNacimiento, string str_pDireccion, string str_pCorreoElectronico, string str_pTelefono, string str_pPersonaAnterior, string str_pClasePersona, string str_pTipoDocumentoPago) {
            UPAdmPre.BL.serviceWSSpring.WM_InsertarClienteRequest inValue = new UPAdmPre.BL.serviceWSSpring.WM_InsertarClienteRequest();
            inValue.Body = new UPAdmPre.BL.serviceWSSpring.WM_InsertarClienteRequestBody();
            inValue.Body.str_pApellidoPaterno = str_pApellidoPaterno;
            inValue.Body.str_pApellidoMaterno = str_pApellidoMaterno;
            inValue.Body.str_pNombres = str_pNombres;
            inValue.Body.str_pRazonSocial = str_pRazonSocial;
            inValue.Body.str_pTipoDocumento = str_pTipoDocumento;
            inValue.Body.str_pNumeroDocumento = str_pNumeroDocumento;
            inValue.Body.str_pDocumentoFiscal = str_pDocumentoFiscal;
            inValue.Body.str_pFechaNacimiento = str_pFechaNacimiento;
            inValue.Body.str_pDireccion = str_pDireccion;
            inValue.Body.str_pCorreoElectronico = str_pCorreoElectronico;
            inValue.Body.str_pTelefono = str_pTelefono;
            inValue.Body.str_pPersonaAnterior = str_pPersonaAnterior;
            inValue.Body.str_pClasePersona = str_pClasePersona;
            inValue.Body.str_pTipoDocumentoPago = str_pTipoDocumentoPago;
            UPAdmPre.BL.serviceWSSpring.WM_InsertarClienteResponse retVal = ((UPAdmPre.BL.serviceWSSpring.WSSpringSoap)(this)).WM_InsertarCliente(inValue);
            return retVal.Body.WM_InsertarClienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPAdmPre.BL.serviceWSSpring.WM_ListarCronogramaPagosResponse UPAdmPre.BL.serviceWSSpring.WSSpringSoap.WM_ListarCronogramaPagos(UPAdmPre.BL.serviceWSSpring.WM_ListarCronogramaPagosRequest request) {
            return base.Channel.WM_ListarCronogramaPagos(request);
        }
        
        public string WM_ListarCronogramaPagos(string str_pCentroCosto, string str_pProyecto, string str_pPeriodo) {
            UPAdmPre.BL.serviceWSSpring.WM_ListarCronogramaPagosRequest inValue = new UPAdmPre.BL.serviceWSSpring.WM_ListarCronogramaPagosRequest();
            inValue.Body = new UPAdmPre.BL.serviceWSSpring.WM_ListarCronogramaPagosRequestBody();
            inValue.Body.str_pCentroCosto = str_pCentroCosto;
            inValue.Body.str_pProyecto = str_pProyecto;
            inValue.Body.str_pPeriodo = str_pPeriodo;
            UPAdmPre.BL.serviceWSSpring.WM_ListarCronogramaPagosResponse retVal = ((UPAdmPre.BL.serviceWSSpring.WSSpringSoap)(this)).WM_ListarCronogramaPagos(inValue);
            return retVal.Body.WM_ListarCronogramaPagosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPAdmPre.BL.serviceWSSpring.WM_ListarDocumentosResumenResponse UPAdmPre.BL.serviceWSSpring.WSSpringSoap.WM_ListarDocumentosResumen(UPAdmPre.BL.serviceWSSpring.WM_ListarDocumentosResumenRequest request) {
            return base.Channel.WM_ListarDocumentosResumen(request);
        }
        
        public string WM_ListarDocumentosResumen(string str_pCliente) {
            UPAdmPre.BL.serviceWSSpring.WM_ListarDocumentosResumenRequest inValue = new UPAdmPre.BL.serviceWSSpring.WM_ListarDocumentosResumenRequest();
            inValue.Body = new UPAdmPre.BL.serviceWSSpring.WM_ListarDocumentosResumenRequestBody();
            inValue.Body.str_pCliente = str_pCliente;
            UPAdmPre.BL.serviceWSSpring.WM_ListarDocumentosResumenResponse retVal = ((UPAdmPre.BL.serviceWSSpring.WSSpringSoap)(this)).WM_ListarDocumentosResumen(inValue);
            return retVal.Body.WM_ListarDocumentosResumenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPAdmPre.BL.serviceWSSpring.WM_ListarDocumentosDetalleResponse UPAdmPre.BL.serviceWSSpring.WSSpringSoap.WM_ListarDocumentosDetalle(UPAdmPre.BL.serviceWSSpring.WM_ListarDocumentosDetalleRequest request) {
            return base.Channel.WM_ListarDocumentosDetalle(request);
        }
        
        public string WM_ListarDocumentosDetalle(string str_pCliente, string str_pCentroCosto, string str_pProyecto) {
            UPAdmPre.BL.serviceWSSpring.WM_ListarDocumentosDetalleRequest inValue = new UPAdmPre.BL.serviceWSSpring.WM_ListarDocumentosDetalleRequest();
            inValue.Body = new UPAdmPre.BL.serviceWSSpring.WM_ListarDocumentosDetalleRequestBody();
            inValue.Body.str_pCliente = str_pCliente;
            inValue.Body.str_pCentroCosto = str_pCentroCosto;
            inValue.Body.str_pProyecto = str_pProyecto;
            UPAdmPre.BL.serviceWSSpring.WM_ListarDocumentosDetalleResponse retVal = ((UPAdmPre.BL.serviceWSSpring.WSSpringSoap)(this)).WM_ListarDocumentosDetalle(inValue);
            return retVal.Body.WM_ListarDocumentosDetalleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPAdmPre.BL.serviceWSSpring.WM_TraerEstadoDeudaResponse UPAdmPre.BL.serviceWSSpring.WSSpringSoap.WM_TraerEstadoDeuda(UPAdmPre.BL.serviceWSSpring.WM_TraerEstadoDeudaRequest request) {
            return base.Channel.WM_TraerEstadoDeuda(request);
        }
        
        public string WM_TraerEstadoDeuda(string str_pCliente) {
            UPAdmPre.BL.serviceWSSpring.WM_TraerEstadoDeudaRequest inValue = new UPAdmPre.BL.serviceWSSpring.WM_TraerEstadoDeudaRequest();
            inValue.Body = new UPAdmPre.BL.serviceWSSpring.WM_TraerEstadoDeudaRequestBody();
            inValue.Body.str_pCliente = str_pCliente;
            UPAdmPre.BL.serviceWSSpring.WM_TraerEstadoDeudaResponse retVal = ((UPAdmPre.BL.serviceWSSpring.WSSpringSoap)(this)).WM_TraerEstadoDeuda(inValue);
            return retVal.Body.WM_TraerEstadoDeudaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPAdmPre.BL.serviceWSSpring.WM_InsertarCobranzaResponse UPAdmPre.BL.serviceWSSpring.WSSpringSoap.WM_InsertarCobranza(UPAdmPre.BL.serviceWSSpring.WM_InsertarCobranzaRequest request) {
            return base.Channel.WM_InsertarCobranza(request);
        }
        
        public string WM_InsertarCobranza(string str_pCodigoCompania, string str_pCodigoCliente, string str_pFechaPreparacion, string str_pCodigoCobrador, string str_pCodigoCajero, string str_pTipoDocumento, string str_pNumeroDocumento, string str_pMonedaPago, string str_pMontoPagado, string str_pTipoPago, string str_pDocumentoReferencia) {
            UPAdmPre.BL.serviceWSSpring.WM_InsertarCobranzaRequest inValue = new UPAdmPre.BL.serviceWSSpring.WM_InsertarCobranzaRequest();
            inValue.Body = new UPAdmPre.BL.serviceWSSpring.WM_InsertarCobranzaRequestBody();
            inValue.Body.str_pCodigoCompania = str_pCodigoCompania;
            inValue.Body.str_pCodigoCliente = str_pCodigoCliente;
            inValue.Body.str_pFechaPreparacion = str_pFechaPreparacion;
            inValue.Body.str_pCodigoCobrador = str_pCodigoCobrador;
            inValue.Body.str_pCodigoCajero = str_pCodigoCajero;
            inValue.Body.str_pTipoDocumento = str_pTipoDocumento;
            inValue.Body.str_pNumeroDocumento = str_pNumeroDocumento;
            inValue.Body.str_pMonedaPago = str_pMonedaPago;
            inValue.Body.str_pMontoPagado = str_pMontoPagado;
            inValue.Body.str_pTipoPago = str_pTipoPago;
            inValue.Body.str_pDocumentoReferencia = str_pDocumentoReferencia;
            UPAdmPre.BL.serviceWSSpring.WM_InsertarCobranzaResponse retVal = ((UPAdmPre.BL.serviceWSSpring.WSSpringSoap)(this)).WM_InsertarCobranza(inValue);
            return retVal.Body.WM_InsertarCobranzaResult;
        }
    }
}
